config/routes.rb
Fsj::Application.routes.draw do

  resources :users
  match 'login' => 'users#login', :as => "login"
  match 'users/:id/logout' => 'users#logout', :as => "logout"
  match 'users/:id/reject_job' => 'users#reject_job', :as => 'reject_job'
  
  resources :jobs

  root :to => "users#index"

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  
  belongs_to :job
  
end

app/models/job.rb
class Job < ActiveRecord::Base
  
  belongs_to :user
  has_many :assignments
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :jobs
  
  validates_presence_of :email, :aesop_id
  validates_uniqueness_of :email, :aesop_id
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i  #This regex has not been tested
  
  attr_accessor :response_code, :headers_hash, :response_body
  
  def User.registered?(aesop_id)
    User.find_by_aesop_id(aesop_id) ? true : false
  end
  
  def set_response_details(response)
    @response_code = response.code
    @headers_hash = response.headers_hash
    @response_body = response.body
    #f = File.open( "/Users/jobluz/Desktop/response_body.html", "w" )
    #f.write(response.body)
    parse_and_save_cookies(response.headers_hash["Set-Cookie"])
  end
  
  def parse_and_save_cookies(cookies)
    if cookies.kind_of?(Array)
      attribute_hash = {}
      cookies.each do |c|
        attribute_hash[:guid] = c.gsub(" path=/", "") if c.include? "GUID="
        attribute_hash[:session_id] = c.gsub(" path=/", "") if c.include? "ASPSESSIONID"
        self.update_attributes(attribute_hash)
      end
    elsif cookies.kind_of?(String) && !cookies.nil?
      self.update_attribute(:session_id, cookies)
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  
  include AesopConnectHelper, HtmlParseHelper
  layout "application"
  
  before_filter :find_user, :only => [:index, :show, :new]
  before_filter :find_job, :only => [:show, :update]
  
  def index
  end
  
  def show
  end
  
  def create
  end
  
  def new
    if aesop_details_page(@user, params[:absr_id])
      @job = get_details_for_accept(@user.response_body)
      if aesop_accept_job(@user, @job.hcc, params[:absr_id])
        @job.save
        flash[:notice] = "You have accepted this job!"
        redirect_to @job
      else
        flash[:notice] = "Job accept failed! You may need to logout and log back in, or the job may no longer be available."
        redirect_to :controller => "users", :action => "show", :id => @user.id
      end      
    else
      flash[:notice] = "Job accept failed! You may need to logout and log back in, or the job may no longer be available."
      redirect_to :controller => "users", :action => "show", :id => @user.id
    end
  end
  
  def update
  end
  
  def destroy
    
  end
  
  def find_user
    @user = User.find(params[:user_id])
  end
  
  def find_job
    @job = Job.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  include AesopConnectHelper, HtmlParseHelper
  layout "application"
  
  before_filter :find_user, :only => [:show, :logout, :accept_job, :reject_job]
  
  def index
  end
  
  def new
  end
  
  def create
    if User.registered?(params[:user][:aesop_id])
      flash[:reg_error] = "There is already a user with that Aesop id!"
    else
      @user = User.new do |u|
        u.aesop_id = params[:user][:aesop_id]
        u.email = params[:user][:email]
        u.user_agent = request.headers["HTTP_USER_AGENT"]
      end
      if login_aesop(@user, params[:user][:aesop_pin])
        if @user.save
          redirect_to @user and return
        else
          flash[:reg_error] = "Registration Failed!"
        end
      else
        flash[:reg_error] = "Failed to login to Aesop!\nEither your Aesop id or Aesop pin is incorrect."
      end
    end
    redirect_to root_path
  end
  
  def update
  end
  
  def destroy
  end
  
  def show
    if aesop_job_list(@user)
      @districts_with_jobs = scrape_district_info(@user.response_body)
    else
      redirect_to root_path
    end
    if request.xhr?
      render :partial => "job_list"
    end
  end
  
  def edit
  end
  
  def login
    @user = User.find_by_email(params[:user][:email])
    if @user
      if login_aesop(@user, params[:user][:aesop_pin])
        redirect_to @user and return
      else
        flash[:login_error] = "Failed to login to Aesop!\nEither your Aesop id or Aesop pin is incorrect."
      end
    else
      flash[:login_error] = "You are not registered with FreeSubJobs.org!"
    end
    redirect_to root_path
  end
  
  def logout
    aesop_logout(@user)
    redirect_to root_path
  end
  
  def reject_job
    if aesop_details_page(@user, params[:absr_id])
      hcc = get_details_for_reject(@user.response_body)
      if aesop_reject_job(@user, hcc, params[:absr_id])
        flash[:notice] = "You have rejected a job"
        redirect_to @user
      else
        flash[:notice] = "Job reject failed! You may need to logout and log back in, or the job may no longer be available."
        redirect_to @user
      end      
    else
      flash[:notice] = "Job reject failed! You may need to logout and log back in, or the job may no longer be available."
      redirect_to @user
    end
  end
  
  def find_user
    @user = User.find_by_id(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/jobs/index.html.haml
= render :partial => "shared/top_menu"

#title
  #sub_title
    Accepted Jobs
  - unless @jobs.nil?
    - @user.jobs.each do |j|
      .rounded_list_container
        .rounded_1.center
        .rounded_2.center
        .rounded_list_item.center
          .rounded_list_title
            = j.assignments[0].date
          %table.scheduled_job{:id => j.id, :class => "#{cycle('odd', 'even')}"}
            %thead
              %th Teacher
              %th School
              %th Subject
              %th Room
              %th Time
              %th Duration
            %tbody
              %tr
                %td.center_text= j.assignments[0].teacher
                %td.center_text= j.assignments[0].school
                %td.center_text= j.assignments[0].subject
                %td.center_text= j.assignments[0].room
                %td.center_text= j.assignments[0].time
                %td.center_text= j.assignments[0].duration
        .rounded_2.center
        .rounded_1.center
  - else
    %center
      You have not accepted any jobs

:javascript
  $(document).ready(function(){
    $(".scheduled_job").click(function(){
      var jobId = $(this).attr("id");
      window.location.href ="/jobs/"+jobId+"?user_id=#{@user.id}";
    });
  });

app/views/jobs/show.html.haml
= render :partial => "shared/top_menu"

#title
  #sub_title
    Job Starting
    = @job.assignments[0].date
  
  .rounded_list_container
    .rounded_1.center
    .rounded_2.center
    .rounded_list_item.center
      .rounded_list_title
        = @job.assignments[0].date
      #job_notes
        = @job.notes
      %table.scheduled_job{:cellpadding => 0, :cellspacing => 0}
        %thead
          %th Teacher
          %th School
          %th Subject
          %th Room
          %th Phone Number
          %th Date
          %th Time
          %th Duration
        - @job.assignments.each do |assignment|
          %tbody{:class => "#{cycle('odd', 'even')}"}
            %tr
              %td= assignment.teacher
              %td= assignment.school
              %td= assignment.subject
              %td= assignment.room
              %td= assignment.phone_number
              %td= assignment.date
              %td= assignment.time
              %td= assignment.duration
    .rounded_2.center
    .rounded_1.center

app/views/layouts/application.html.haml
!!! 1.0
%html{:xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %title
      FreeSubJobs.org
    = stylesheet_link_tag "application", "../javascripts/jquery-ui-1.8.9.custom/css/smoothness/jquery-ui-1.8.9.custom.css"
    = javascript_include_tag "jquery-ui-1.8.9.custom/js/jquery-1.4.4.min.js", "jquery-ui-1.8.9.custom/js/jquery-ui-1.8.9.custom.min.js", "job_list_controls.js"
  
  %body
    #main_wrap
      #main_banner
        .left_text
          FreeSubJobs.com
        .clear
      
      = yield
      
      #main_footer
        %center
          FreeSubJobs.com 2010
          - if Time.now.year > 2010
            = " - #{Time.now.year}"

app/views/shared/_top_menu.html.haml
.menu_item.left
  = link_to "Look For Jobs", user_path(@user.id)
.menu_item.left
  = link_to "View My Jobs", jobs_path({:user_id => @user.id})
.menu_item.right
  = link_to "Logout", logout_path(@user.id)
.clear

app/views/users/_accepted_job.html.haml
You have accepted the job!

- #TODO: include option to cancel job. How to do this? Either pass them in via javascript when the xhr request is made, or parse them from job details page.

app/views/users/_job_list.html.haml
- unless @districts_with_jobs.empty?
  .notice
    - if flash[:notice]
      = flash[:notice]
  - @districts_with_jobs.each do |district, jb|
    - unless jb.empty?
      .rounded_list_container
        .rounded_1.center
        .rounded_2.center
        .rounded_list_title
          = district.name
        - jb.each do |j|
          %table.rounded_list_item{:class => "#{cycle('odd', 'even')}", :name => "#{j.absr_id}"}
            %tr
              %td
                %table{:class => "job_for_district"}
                  %tr
                    %td.date_td
                      = j.assignments[0].date
                    %td
                      %div
                        = j.assignments[0].subject
                      %div
                      = #link_to( "Exclude", )
                    %td
                      = j.assignments[0].teacher
                    %td
                      = j.assignments[0].school
              %td.reject_button
                %img.reject{:src => '/images/red-circle-slash.png', :name => "#{j.absr_id}"}
              %td.accept_button
                %a{:class => "accept", :name => "#{j.absr_id}", :href => "/jobs/new?absr_id=#{j.absr_id}&user_id=#{@user.id}"}
                  %img{:src => '/images/green-plus.png'}
              %td.spinner
                %img{:src => "/images/spinner.gif", :alt => "spinner"}
            %tr{:class => "job_details", :name => "#{j.absr_id}"}
              %td{:class => "job_details_table"}
                %table
                  %thead
                    %tr
                      %th Day
                      %th Start
                      %th End
                      %th Duration
                      %th School
                  %tbody
                    - j.assignments.each do |assignment|
                      %tr
                        %td= assignment.date
                        %td= assignment.start_time
                        %td= assignment.end_time
                        %td= assignment.duration
                        %td= assignment.school
        .rounded_2.center
        .rounded_1.center

    .hidden_sound
      - #%audio{:src => "/audio/buzzer.ogg", :autoplay => "autoplay"}
- else
  %center
    There are no jobs at this time.

:javascript
  $(document).ready(function(){
    $(".rounded_list_item").click(function(){
      toggleJobDetails($(this).attr("name"));
    });
    
    $(".reject").click(function(){
      absrId = $(this).attr("name");
      var confirmed = confirm("Are you sure you want to reject this job?")
      if (confirmed){ window.location = "#{@user.id}/reject_job?absr_id="+absrId; }
    });
  });

app/views/users/_rejected_job.html.haml
You have rejected this job.

app/views/users/index.html.haml
#how_it_works
  .index_title
    How It Works
  FreeSubJobs.com automatically searches for substitute jobs. No more clicking the refresh button or "Search Again"! 
  %p Simply Log in, and watch as this site does the hard work. You will be notified when a job is found.
  %p FreeSubJobs.com does not automatically accept jobs for you, as that is against the Aesop User Agreement. You will have to click the "Accept" button to accept a job.


- if flash[:general_notice]
  .notice
    = flash[:general_notice]

#login_register_forms.center
  #login_form.left
    .index_title
      Login
    .subtitle
      I already have a FreeSubJobs.com account.
    - form_for :user, :url => "/login" do |u|
      .label
        %label
          Email
      = u.text_field :email, {:class => "textbox", :size => "15"}
      .label
        %label
          Aesop Pin
      = u.password_field :aesop_pin, {:type => "password", :class => "textbox", :size => "15"}
      %br
      = submit_tag "Login", {:class => "button"}
    - if flash[:login_error]
      .notice
        = flash[:login_error]
      
  #register_form.left
    .index_title
      Register
    .subtitle
      I have never used this site before.
    - form_for :user, :url => "/users" do |u|
      .label
        %label
          Email
      = u.text_field :email, {:class => "textbox", :size => "15"}
      .label
        %label
          Aesop Id
      = u.text_field :aesop_id, {:class => "textbox", :size => "15"}
      .label
        %label
          Aesop Pin
      = u.password_field :aesop_pin, {:class => "textbox", :type => "password", :size => "15"}
      %br
      = submit_tag "Register", {:class => "button"}
    - if flash[:reg_error]
      .notice
        = flash[:reg_error]

  .clear

%center
  #more_info_links
    = link_to "Is my information secure?", "#", {:name => "security"}

#security
  .dialog_text
    FreeSubJobs.com is a secure way to easily access your Aesop substitute teacher account and find substitute jobs. The information you enter here is 
    sent over a secure channel.
    %p FreeSubJobs.com does not store your Aesop Pin. Your email address is only used to login. 
    %p Your email address will never be sold or sent to another organization or business. 
    %p You might receive an email (very rarely, if ever) to provide an update about important changes to the site. You will never receive spam or advertisements. 
    %p You must already have an Aesop id and pin to create an account with FreeSubJobs.com.

:javascript
  $(document).ready(function(){
    $("#security").dialog({ 
      autoOpen: false,
      title: "Is My Information Secure?",
      width: 600,
      height: 420,
      modal: true
    });
    $("#more_info_links a").click(function(){
      dialogToOpenId = $(this).attr("name");
      $("#"+dialogToOpenId).dialog("open");
    });
  });

app/views/users/show.html.haml
= render :partial => "shared/top_menu"

#title
  #subject_preferences
    #sub_title
      Jobs Available
  #jobs_list.center
    = render :partial => "users/job_list"
  .clear

:javascript
  startJobListRefresher(#{@user.id})